"""Exporter — a CrewForge spec -> a portable, runnable CrewAI project.

This is the no-lock-in guarantee: anything you build in the studio can be exported
to an idiomatic crewai project (config YAML + a small runner) and run standalone
with `crewai`/`python main.py`. Returns {relative_path: file_contents}.
"""
from __future__ import annotations

import io
import re
import zipfile
from typing import Any

import yaml


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_") or "crew"


def _llm_wire(llm_id: str | None) -> str | None:
    """Resolve a configured connection id to its provider/model wire string."""
    if not llm_id:
        return None
    try:
        from .. import llms
        cfg = llms.resolve(llm_id)
        return cfg.get("model") if cfg else None
    except Exception:  # noqa: BLE001 - export must work without a configured store
        return None


def _tool_args(tool_names: set[str]) -> dict[str, dict[str, Any]]:
    """Non-secret constructor args for configured built-in tools (env keys are
    never exported — the user sets those in their own environment)."""
    out: dict[str, dict[str, Any]] = {}
    try:
        from .. import builtin_tools
        for n in sorted(tool_names):
            if builtin_tools.describe(n) is None:
                continue
            args = builtin_tools.get_config(n).get("args") or {}
            out[n] = args
    except Exception:  # noqa: BLE001 - export must work without a configured store
        pass
    return out


def export_files(spec: dict[str, Any]) -> dict[str, str]:
    name = spec.get("name", "Crew")
    slug = _slug(name)

    workflow_skills = list(spec.get("skills") or [])
    agents_yaml = {}
    for a in spec.get("agents", []):
        entry = {"role": a["role"], "goal": a["goal"], "backstory": a["backstory"]}
        wire = _llm_wire(a.get("llm_id"))
        if wire:
            entry["llm"] = wire
        skills = list(dict.fromkeys(list(a.get("tools") or []) + workflow_skills))
        if skills:
            entry["tools"] = skills
        agents_yaml[a["id"]] = entry
    task_keys = [t.get("name") or f"task_{i + 1}" for i, t in enumerate(spec.get("tasks", []))]
    tasks_yaml = {}
    for i, t in enumerate(spec.get("tasks", [])):
        key = task_keys[i]
        tasks_yaml[key] = {
            "description": t["description"],
            "expected_output": t["expected_output"],
            "agent": t["agent"],
        }
        if t.get("async_execution"):
            tasks_yaml[key]["async_execution"] = True
        ctx_keys = [task_keys[c] for c in (t.get("context") or [])
                    if isinstance(c, int) and 0 <= c < i]
        if ctx_keys:
            tasks_yaml[key]["context"] = ctx_keys
        cond = t.get("condition") or {}
        if i > 0 and cond.get("check") in ("contains", "not_contains", "regex"):
            tasks_yaml[key]["condition"] = {
                "check": cond["check"], "value": str(cond.get("value") or ""),
                **({"case_sensitive": True} if cond.get("case_sensitive") else {}),
            }

    process = "Process.hierarchical" if spec.get("process") == "hierarchical" else "Process.sequential"
    mgr_id = spec.get("manager_agent_id") if spec.get("process") == "hierarchical" else None
    assigned = {t.get("agent") for t in spec.get("tasks", [])}
    if mgr_id not in agents_yaml or mgr_id in assigned:
        mgr_id = None  # same rule as the adapter: a manager can't own tasks
    mgr_line = f'\n    manager = agents.pop("{mgr_id}")' if mgr_id else ""
    mgr_kwarg = ", manager_agent=manager" if mgr_id else ""

    all_skill_names: set[str] = set(workflow_skills)
    for a in spec.get("agents", []):
        all_skill_names |= set(a.get("tools") or [])
    tools_yaml = _tool_args(all_skill_names)

    crew_py = f'''"""{name} — generated by CrewForge (https://github.com/Arturski/CrewForge)."""
import re
from pathlib import Path

import yaml
from crewai import Agent, Crew, Process, Task
from crewai.tasks.conditional_task import ConditionalTask

_HERE = Path(__file__).parent


def _load(rel: str) -> dict:
    return yaml.safe_load((_HERE / rel).read_text())


def _build_tools(names: list[str], tools_cfg: dict) -> list:
    """Instantiate built-in crewai_tools by name (set provider keys via env).
    Names that aren't crewai_tools classes (e.g. MCP tools) are skipped."""
    out = []
    try:
        import crewai_tools
    except ImportError:
        return out
    for n in names:
        cls = getattr(crewai_tools, n, None)
        if isinstance(cls, type):
            out.append(cls(**(tools_cfg.get(n) or {{}})))
    return out


def _condition(cfg: dict):
    """No-code run condition: test the previous task's output."""
    check, value = cfg.get("check"), str(cfg.get("value") or "")
    case_sensitive = bool(cfg.get("case_sensitive"))

    def predicate(output) -> bool:
        text = str(getattr(output, "raw", output) or "")
        if check == "regex":
            return re.search(value, text, 0 if case_sensitive else re.IGNORECASE) is not None
        t, v = (text, value) if case_sensitive else (text.lower(), value.lower())
        return (v in t) if check == "contains" else (v not in t)

    return predicate


def build_crew() -> Crew:
    agents_cfg = _load("config/agents.yaml")
    tasks_cfg = _load("config/tasks.yaml")
    tools_cfg = _load("config/tools.yaml") if (_HERE / "config/tools.yaml").exists() else {{}}

    agents = {{}}
    for key, cfg in agents_cfg.items():
        tool_names = cfg.pop("tools", [])
        agents[key] = Agent(**cfg, tools=_build_tools(tool_names, tools_cfg)){mgr_line}
    tasks, by_key = [], {{}}
    for key, cfg in tasks_cfg.items():
        kwargs = dict(
            description=cfg["description"],
            expected_output=cfg["expected_output"],
            agent=agents[cfg["agent"]],
        )
        if cfg.get("async_execution"):
            kwargs["async_execution"] = True
        if cfg.get("context"):
            kwargs["context"] = [by_key[k] for k in cfg["context"] if k in by_key]
        if cfg.get("condition"):
            task = ConditionalTask(condition=_condition(cfg["condition"]), **kwargs)
        else:
            task = Task(**kwargs)
        by_key[key] = task
        tasks.append(task)
    return Crew(agents=list(agents.values()), tasks=tasks,
                process={process}, verbose=True{mgr_kwarg})
'''

    main_py = f'''"""Run the {name} crew. Set your provider key (e.g. OPENAI_API_KEY) first."""
from crew import build_crew

if __name__ == "__main__":
    result = build_crew().kickoff()
    print(result)
'''

    pyproject = f'''[project]
name = "{slug}"
version = "0.1.0"
description = "{name} — a CrewAI crew exported from CrewForge"
requires-python = ">=3.10,<3.14"
dependencies = ["crewai>=1.0", "pyyaml"]
'''

    readme = f'''# {name}

Exported from [CrewForge](https://github.com/Arturski/CrewForge) — a no-code studio for CrewAI.
This is a standard, self-contained CrewAI project.

```bash
pip install -r <(echo "crewai\\npyyaml")   # or: uv sync
export OPENAI_API_KEY=...                   # or your provider of choice
python main.py
```

Edit `config/agents.yaml` and `config/tasks.yaml` to change the crew.
Built-in tools read their provider keys from the environment (e.g. `SERPER_API_KEY`);
non-secret tool options live in `config/tools.yaml`.
'''

    files = {
        "crew.py": crew_py,
        "main.py": main_py,
        "pyproject.toml": pyproject,
        "README.md": readme,
        "config/agents.yaml": yaml.safe_dump(agents_yaml, sort_keys=False, allow_unicode=True),
        "config/tasks.yaml": yaml.safe_dump(tasks_yaml, sort_keys=False, allow_unicode=True),
    }
    if tools_yaml:
        files["config/tools.yaml"] = yaml.safe_dump(tools_yaml, sort_keys=False, allow_unicode=True)
    return files


def export_zip(spec: dict[str, Any]) -> bytes:
    files = export_files(spec)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        root = _slug(spec.get("name", "crew"))
        for path, content in files.items():
            z.writestr(f"{root}/{path}", content)
    return buf.getvalue()
