"""Exporter — a CrewForge spec -> a portable, runnable CrewAI project.

This is the no-lock-in guarantee: anything you build in the studio can be exported
to an idiomatic crewai project (config YAML + a small runner) and run standalone
with `crewai`/`python main.py`. Returns {relative_path: file_contents}.
"""
from __future__ import annotations

import io
import re
import zipfile
from typing import Any

import yaml


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_") or "crew"


def export_files(spec: dict[str, Any]) -> dict[str, str]:
    name = spec.get("name", "Crew")
    slug = _slug(name)

    workflow_skills = list(spec.get("skills") or [])
    agents_yaml = {}
    for a in spec.get("agents", []):
        entry = {"role": a["role"], "goal": a["goal"], "backstory": a["backstory"]}
        if a.get("llm_model"):
            entry["llm"] = a["llm_model"]
        skills = list(dict.fromkeys(list(a.get("tools") or []) + workflow_skills))
        if skills:
            entry["tools"] = skills
        agents_yaml[a["id"]] = entry
    tasks_yaml = {}
    for i, t in enumerate(spec.get("tasks", [])):
        key = t.get("name") or f"task_{i + 1}"
        tasks_yaml[key] = {
            "description": t["description"],
            "expected_output": t["expected_output"],
            "agent": t["agent"],
        }
        if t.get("async_execution"):
            tasks_yaml[key]["async_execution"] = True

    process = "Process.hierarchical" if spec.get("process") == "hierarchical" else "Process.sequential"

    crew_py = f'''"""{name} — generated by CrewForge (https://github.com/Arturski/CrewForge)."""
from pathlib import Path

import yaml
from crewai import Agent, Crew, Process, Task

_HERE = Path(__file__).parent


def _load(rel: str) -> dict:
    return yaml.safe_load((_HERE / rel).read_text())


def build_crew() -> Crew:
    agents_cfg = _load("config/agents.yaml")
    tasks_cfg = _load("config/tasks.yaml")

    agents = {{key: Agent(**cfg) for key, cfg in agents_cfg.items()}}
    tasks = [
        Task(
            description=cfg["description"],
            expected_output=cfg["expected_output"],
            agent=agents[cfg["agent"]],
        )
        for cfg in tasks_cfg.values()
    ]
    return Crew(agents=list(agents.values()), tasks=tasks,
                process={process}, verbose=True)
'''

    main_py = f'''"""Run the {name} crew. Set your provider key (e.g. OPENAI_API_KEY) first."""
from crew import build_crew

if __name__ == "__main__":
    result = build_crew().kickoff()
    print(result)
'''

    pyproject = f'''[project]
name = "{slug}"
version = "0.1.0"
description = "{name} — a CrewAI crew exported from CrewForge"
requires-python = ">=3.10,<3.14"
dependencies = ["crewai>=1.0", "pyyaml"]
'''

    readme = f'''# {name}

Exported from [CrewForge](https://github.com/Arturski/CrewForge) — a no-code studio for CrewAI.
This is a standard, self-contained CrewAI project.

```bash
pip install -r <(echo "crewai\\npyyaml")   # or: uv sync
export OPENAI_API_KEY=...                   # or your provider of choice
python main.py
```

Edit `config/agents.yaml` and `config/tasks.yaml` to change the crew.
'''

    return {
        "crew.py": crew_py,
        "main.py": main_py,
        "pyproject.toml": pyproject,
        "README.md": readme,
        "config/agents.yaml": yaml.safe_dump(agents_yaml, sort_keys=False, allow_unicode=True),
        "config/tasks.yaml": yaml.safe_dump(tasks_yaml, sort_keys=False, allow_unicode=True),
    }


def export_zip(spec: dict[str, Any]) -> bytes:
    files = export_files(spec)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        root = _slug(spec.get("name", "crew"))
        for path, content in files.items():
            z.writestr(f"{root}/{path}", content)
    return buf.getvalue()
