import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, type Manifest, type WorkspaceSummary } from "../lib/api";
import { Badge, Button, Card, CardHeader, Pill } from "../components/ui";

export function Dashboard() {
  const [manifest, setManifest] = useState<Manifest | null>(null);
  const [workspaces, setWorkspaces] = useState<WorkspaceSummary[]>([]);

  useEffect(() => {
    api.manifest().then(setManifest).catch(() => {});
    api.workspaces().then((d) => setWorkspaces(d.workspaces)).catch(() => {});
  }, []);

  const total = manifest ? Object.values(manifest.counts).reduce((a, b) => a + b, 0) : 0;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-ink">Dashboard</h1>
        <p className="text-sm text-muted">Build, run, and observe CrewAI workflows with no code.</p>
      </div>

      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <Stat label="crewai version" value={manifest?.crewai_version ?? "…"} tone="brand" />
        <Stat label="fields auto-discovered" value={total ? String(total) : "…"} tone="ok" />
        <Stat label="hardcoded fields" value="0" tone="ok" />
        <Stat label="workspaces" value={String(workspaces.length)} tone="muted" />
      </div>

      <Card>
        <CardHeader
          title="Compatibility engine"
          sub="Config forms are generated by introspecting the installed crewai — new fields surface automatically."
        />
        <div className="flex flex-wrap gap-2 p-4">
          {manifest &&
            Object.entries(manifest.counts).map(([m, n]) => (
              <Pill key={m} color="var(--color-node-agent)">{m}: {n} fields</Pill>
            ))}
        </div>
      </Card>

      <Card>
        <CardHeader title="Workspaces" sub="Open a workspace in the Builder, then run it." />
        <div className="divide-y divide-border">
          {workspaces.map((w) => (
            <div key={w.id} className="flex items-center justify-between gap-4 px-4 py-3">
              <div>
                <div className="font-medium text-ink">{w.name}</div>
                <div className="text-xs text-muted">{w.description}</div>
              </div>
              <div className="flex items-center gap-2">
                <Badge tone="muted">{w.agents} agents</Badge>
                <Badge tone="muted">{w.tasks} tasks</Badge>
                <Link to={`/builder?ws=${w.id}`}><Button variant="ghost">Open</Button></Link>
              </div>
            </div>
          ))}
          {workspaces.length === 0 && <div className="px-4 py-6 text-sm text-muted">Loading…</div>}
        </div>
      </Card>
    </div>
  );
}

function Stat({ label, value, tone }: { label: string; value: string; tone: "brand" | "ok" | "muted" }) {
  const color = tone === "brand" ? "text-brand" : tone === "ok" ? "text-ok" : "text-ink";
  return (
    <Card className="p-4">
      <div className="text-xs text-muted">{label}</div>
      <div className={`mt-1 text-2xl font-semibold ${color}`}>{value}</div>
    </Card>
  );
}
